I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 252, in script
    if assholeToAugust == true:
  File "game/script.rpy", line 252, in <module>
    if assholeToAugust == true:
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 252, in script
    if assholeToAugust == true:
  File "C:\Users\Andrea Mantke\Downloads\renpy-7.4.8-sdk/renpy/ast.py", line 1893, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Andrea Mantke\Downloads\renpy-7.4.8-sdk/renpy/python.py", line 2266, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Andrea Mantke\Downloads\renpy-7.4.8-sdk/renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 252, in <module>
    if assholeToAugust == true:
NameError: name 'true' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
DatingSim 1.0
Thu Dec  2 00:22:23 2021
